function Task = g_InverseKinematics_Task(in1)
%G_INVERSEKINEMATICS_TASK
%    TASK = G_INVERSEKINEMATICS_TASK(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    18-Sep-2020 14:34:28

q1 = in1(1,:);
q2 = in1(2,:);
q3 = in1(3,:);
q5 = in1(5,:);
q6 = in1(6,:);
q8 = in1(8,:);
q9 = in1(9,:);
q11 = in1(11,:);
q12 = in1(12,:);
Task = [sin(q2+q3).*(-3.412758520244684e-4)-sin(q5+q6).*3.412758520244684e-4-sin(q8+q9).*3.412758520244684e-4-sin(q11+q12).*3.412758520244684e-4-sin(q2).*2.041865715117973e-3-sin(q5).*2.041865715117973e-3-sin(q8).*2.041865715117973e-3-sin(q11).*2.041865715117973e-3;q1+q2];
